language: ruby
cache: bundler
sudo: false
before_script:
  - cp config/database.sample.yml config/database.yml
  - cp config/general.sample.yml config/general.yml
  - bundle exec rake --version
  - bundle exec rake -T
  - bundle exec rake assets:download
  - bundle exec rake assets:generate
  - bundle exec rake db:migrate
  - bundle exec rake fixture:admin
  - sqlite3 app.db ".dump"

script: bundle exec rake

addons:
  code_climate:
    repo_token: a18103c8bb694e4732f0e022d64fde84b59c9f586fa3bc6d3abd72e9bdefcb8d

rvm:
    - 2.0.0
    - 1.9.3
