language: ruby
cache: bundler
sudo: false
before_script:
  - bundle exec rake --version
  - bundle exec rake -T
  - bundle exec rake assets:download
  - bundle exec rake assets:generate
  - bundle exec rake db:migrate
  - sqlite3 app.db ".dump"

script: bundle exec rake

rvm:
    - 2.0.0
    - 1.9.3
