language: ruby
cache: bundler
sudo: false
before_script:
  - cp config/database.sample.yml config/database.yml
  - cp config/general.sample.yml config/general.yml
  - bundle exec rake --version
  - bundle exec rake -T
  - bundle exec rake assets:download
  - bundle exec rake assets:generate
  - bundle exec rake db:migrate
  - bundle exec rake fixture:admin
  - sqlite3 app.db ".dump"

script: bundle exec rake

addons:
  code_climate:
    repo_token: aab33f3fbaf13b1d83bb56977ca63bdfb3cbb259fc915bfad094a173170fc705

rvm:
  - 2.0.0
  - 1.9.3

matrix:
  allow_failures:
    - rvm: 1.9.3
