require_relative 'base'
require_relative 'main'
require_relative 'article'
require_relative 'page'
require_relative 'event'
require_relative 'review'
require_relative 'user'
require_relative 'settings'
