parameters:
  base_url: 'http://127.0.0.1:9292'
  title: eee
  slogan: eee
  cover: zzzz.jpg
payment: 
  rib: 
    code_banque: 00
    code_guichet: 00
    numero_compte: 123456
    cle_rib: 00
    domiciliation: 'insa'
    iban: 000
    bic: 0000
  cheque:
    order: 'aa'
    address: 'bb'
  price:
    amount: 42
    currency: '€'
cookies:
  key: 'rack.session'
  path: '/'
  secret: 's3cr3t'
mail:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'localhost.localdomain'
  user_name: 'your.account@gmail.com'
  password: 's3cr3t'
  authentication: 'plain'
  starttls: true
  from: 'your.account@gmail.com'
meal:
  first_day: 20/05/2016
  first_meal: 2
  last_day: 28/05/2016
  last_meal: 0
  breackfast: false
  lunch: true
  dinner: true
