require_relative 'article'
require_relative 'page'
require_relative 'event'
require_relative 'user'
require_relative 'formAnswer'
require_relative 'formElement'
require_relative 'usersFormAnswer'
require_relative 'registeredUsersToEvents'